Repository WonnaBE7/Backend, pull requests merged in 2025-08, with the labels that each got.

#49 [feat] 카드 추천 및 카드 상품 상세 정보 조회
  build.gradle
  src/main/java/com/wonnabe/common/config/RootConfig.java
  src/main/java/com/wonnabe/product/controller/CardApplyController.java
  src/main/java/com/wonnabe/product/controller/CardProductController.java
  src/main/java/com/wonnabe/product/controller/CardRecommendController.java
  src/main/java/com/wonnabe/product/domain/CardProductVO.java
  src/main/java/com/wonnabe/product/domain/enums/CardType.java
  src/main/java/com/wonnabe/product/dto/BasicUserInfo.java
  src/main/java/com/wonnabe/product/dto/CardProductDetailResponseDTO.java
  src/main/java/com/wonnabe/product/dto/CardRecommendationResponseDTO.java
  src/main/java/com/wonnabe/product/dto/UserInfoForCardDTO.java
  src/main/java/com/wonnabe/product/mapper/CardMapper.java
  src/main/java/com/wonnabe/product/service/CardService.java
  src/main/java/com/wonnabe/product/service/CardServiceImpl.java
  src/main/resources/com/wonnabe/product/mapper/CardMapper.xml
  src/test/java/com/wonnabe/product/controller/CardApplyControllerTest.java
  src/test/java/com/wonnabe/product/controller/CardProductControllerTest.java
  src/test/java/com/wonnabe/product/controller/CardRecommendControllerTest.java
  src/test/java/com/wonnabe/product/mapper/CardMapperTest.java
  src/test/java/com/wonnabe/product/service/CardServiceImplTest.java
Labels: feature

#51 [feat] 예적금 신청 API
  src/main/java/com/wonnabe/common/config/RootConfig.java
  src/main/java/com/wonnabe/product/controller/SavingsApplyController.java
  src/main/java/com/wonnabe/product/domain/UserSavingsVO.java
  src/main/java/com/wonnabe/product/dto/SavingsApplyRequestDTO.java
  src/main/java/com/wonnabe/product/mapper/SavingsMapper.java
  src/main/java/com/wonnabe/product/service/SavingsApplyService.java
  src/main/java/com/wonnabe/product/service/SavingsApplyServiceImpl.java
  src/main/resources/com/wonnabe/product/mapper/SavingsMapper.xml
  src/test/java/com/wonnabe/product/controller/SavingsApplyControllerTest.java
  src/test/java/com/wonnabe/product/mapper/SavingsMapperTest.java
  src/test/java/com/wonnabe/product/service/SavingsApplyServiceImplTest.java
Labels: feature

#65 [fix] 계좌 데이터 파서 기능 수정 및 연동 개선
  src/main/java/com/wonnabe/codef/domain/UserAccount.java
  src/main/java/com/wonnabe/codef/domain/UserSaving.java
  src/main/java/com/wonnabe/codef/domain/UserTransactions.java
  src/main/java/com/wonnabe/codef/dto/CardListWrapper.java
  src/main/java/com/wonnabe/codef/dto/SavingTransactionResponse.java
  src/main/java/com/wonnabe/codef/dto/TransactionDetail.java
  src/main/java/com/wonnabe/codef/dto/TransactionListResponse.java
  src/main/java/com/wonnabe/codef/mapper/AssetCardMapper.java
  src/main/java/com/wonnabe/codef/service/AssetSyncService.java
  src/main/resources/com/wonnabe/codef/mapper/AssetCardMapper.xml
  src/main/resources/com/wonnabe/codef/mapper/AssetMapper.xml
  src/main/resources/com/wonnabe/codef/mapper/CodefSavingsMapper.xml
  src/main/resources/com/wonnabe/codef/mapper/UserTransactionsMapper.xml
Labels: bug

#82 [fix] 삭제된 내용 복구 - 커뮤니티 인기 상품 Top3
  src/main/java/com/wonnabe/community/controller/CommunityController.java
Labels: bug

#83 [fix] AuthServiceTest 반환 오류 수정
  src/test/java/com/wonnabe/auth/service/AuthServiceTest.java
Labels: bug

#91 [refactor] API 명세서 변경에 따른 url 변경
  src/main/java/com/wonnabe/product/controller/CardProductController.java
  src/main/java/com/wonnabe/product/controller/UserProductController.java
  src/test/java/com/wonnabe/product/controller/CardProductDetailControllerTest.java
  src/test/java/com/wonnabe/product/controller/UserProductDetailControllerTest.java
Labels: refactor

#93 [fix] DB 변경에 따른 매퍼 수정
  src/main/resources/com/wonnabe/product/mapper/CardMapper.xml
Labels: bug

#101 [Feature] 은행/카드/증권 계좌 연결
  src/main/java/com/wonnabe/asset/controller/ConsumptionTransactionsController.java
  src/main/java/com/wonnabe/codef/client/CodefApiClient.java
  src/main/java/com/wonnabe/codef/domain/CardTransactions.java
  src/main/java/com/wonnabe/codef/domain/UserAccount.java
  src/main/java/com/wonnabe/codef/dto/AccessTokenResponseDto.java
  src/main/java/com/wonnabe/codef/dto/AccountListResponse.java
  src/main/java/com/wonnabe/codef/dto/AccountTransactionListResponse.java
  src/main/java/com/wonnabe/codef/dto/AccountTransactionListWrapper.java
  src/main/java/com/wonnabe/codef/dto/AccountTransactionListWrapperResult.java
  src/main/java/com/wonnabe/codef/dto/CardApprovalListResponse.java
  src/main/java/com/wonnabe/codef/dto/CardTransactionData.java
  src/main/java/com/wonnabe/codef/dto/CardTransactionListWrapper.java
  src/main/java/com/wonnabe/codef/dto/CardTransactionResult.java
  src/main/java/com/wonnabe/codef/dto/InvestAccountListResponse.java
  src/main/java/com/wonnabe/codef/dto/InvestAccountListResult.java
  src/main/java/com/wonnabe/codef/dto/InvestAccountListWrapper.java
  src/main/java/com/wonnabe/codef/dto/SavingListResponse.java
  src/main/java/com/wonnabe/codef/dto/SavingTransactionListResponse.java
  src/main/java/com/wonnabe/codef/dto/TransactionDetail.java
  src/main/java/com/wonnabe/codef/mapper/AssetCardMapper.java
  src/main/java/com/wonnabe/codef/mapper/AssetMapper.java
  src/main/java/com/wonnabe/codef/service/AssetSyncService.java
  src/main/resources/com/wonnabe/asset/mapper/AssetOverviewMapper.xml
  src/main/resources/com/wonnabe/codef/mapper/AssetCardMapper.xml
  src/main/resources/com/wonnabe/codef/mapper/AssetMapper.xml
  src/main/resources/com/wonnabe/codef/mapper/UserTransactionsMapper.xml
Labels: feature

#105 [fix] Product Error
  src/main/java/com/wonnabe/product/controller/InsuranceApplyController.java
  src/main/java/com/wonnabe/product/controller/ProductDetailController.java
  src/main/java/com/wonnabe/product/controller/RecommendInsuranceController.java
  src/main/java/com/wonnabe/product/controller/RecommendSavingsController.java
  src/main/java/com/wonnabe/product/controller/UserInsuranceController.java
  src/main/java/com/wonnabe/product/controller/UserSavingsController.java
  src/main/java/com/wonnabe/product/dto/MonthlyChartDto.java
  src/main/java/com/wonnabe/product/dto/MonthlyInsuranceReceiptDto.java
  src/main/java/com/wonnabe/product/dto/UserInsuranceDetailDTO.java
  src/main/java/com/wonnabe/product/dto/UserSavingsDetailResponseDto.java
  src/main/java/com/wonnabe/product/mapper/UserInsuranceMapper.java
  src/main/java/com/wonnabe/product/service/UserInsuranceServiceImpl.java
  src/main/resources/com/wonnabe/product/mapper/UserInsuranceMapper.xml
  src/test/java/com/wonnabe/product/controller/InsuranceApplyControllerTest.java
  src/test/java/com/wonnabe/product/controller/ProductDetailControllerTest.java
  src/test/java/com/wonnabe/product/controller/RecommendInsuranceControllerTest.java
  src/test/java/com/wonnabe/product/controller/RecommendSavingsControllerTest.java
  src/test/java/com/wonnabe/product/controller/UserInsuranceControllerTest.java
  src/test/java/com/wonnabe/product/controller/UserSavingsControllerTest.java
  src/test/java/com/wonnabe/product/mapper/UserInsuranceMapperTest.java
  src/test/java/com/wonnabe/product/service/UserInsuranceServiceImplTest.java
Labels: bug

#109 [fix] Product 매핑 이름 수정
  src/main/java/com/wonnabe/asset/controller/ConsumptionTransactionsController.java
  src/main/resources/com/wonnabe/product/mapper/SavingsRecommendationMapper.xml
  src/test/java/com/wonnabe/product/controller/RecommendSavingsControllerTest.java
Labels: bug
